### ISSUE TITLE
referee module issue

### ISSUE THREAD

**Issue by srinikethmshenoy** [NightFox-AI/NightFox#8]
The module referee doesnot include the case where the firt player has three in a row and then the second player and fails to see that the first player had 3 in a row but the first player again misses to win in the next chance

**Comment by ndyashas** [comment]
Did you fix it in the recent commit ?

**Comment by srinikethmshenoy** [comment]
no ,that issue needs to predict the future so was planning to drop it.

**Comment by srinikethmshenoy** [comment]
Could u guys send me the final code


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Yashas ND <notifications@github.com> Date: 04/12/2018  15:49  (GMT+05:30) To: NightFox-AI/NightFox <NightFox@noreply.github.com> Cc: srinikethmshenoy <sriniketh2all@gmail.com>, Assign <assign@noreply.github.com> Subject: Re: [NightFox-AI/NightFox] referee module issue (#8) 
Closed #8.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/NightFox-AI/NightFox","title":"NightFox-AI/NightFox","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/NightFox-AI/NightFox"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #8."}],"action":{"name":"View Issue","url":"https://github.com/NightFox-AI/NightFox/issues/8#event-2003846266"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/NightFox-AI/NightFox/issues/8#event-2003846266",
"url": "https://github.com/NightFox-AI/NightFox/issues/8#event-2003846266",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [NightFox-AI/NightFox] referee module issue (#8)",
"sections": [
{
"text": "",
"activityTitle": "**Yashas ND**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@yashasbharadwaj111",
"facts": [

]
}
],
"potentialAction": [
{
"targets": [
{
"os": "default",
"uri": "https://github.com/NightFox-AI/NightFox/issues/8#event-2003846266"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 392830758\n}"
}
],
"themeColor": "26292E"
}
]
